#!/usr/bin/with-contenv bash

sed -i \
    -e 's/memory_limit.*=.*512M/memory_limit=2G/g' \
    -e 's/max_execution_time.*=.*120/max_execution_time=3600/g' \
    -e 's/max_input_time.*=.*60/max_input_time=3600/g' \
    -e 's/upload_max_filesize.*=.*1024M/upload_max_filesize=16G/g' \
    -e 's/post_max_size.*=.*1024M/post_max_size=6G/g' \
    /etc/php8/php.ini